apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{.Values.appname}}    
  name: {{.Values.appname}}
  namespace: {{.Values.namespace.name}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{.Values.appname}}      
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{.Values.appname}} 
    spec:
      containers:
      - image: {{ .Values.image.dockerRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{.Values.image.imagePullPolicy}}
        name: {{.Values.appname}} 
        ports:
            - containerPort: {{.Values.containerPort}}
              protocol: TCP
        livenessProbe:
          httpGet:
            path: {{.Values.livenessProbe.path}}
            port: {{.Values.livenessProbe.port}}
        readinessProbe:
          httpGet:
            path: {{.Values.readinessProbe.path}}
            port: {{.Values.readinessProbe.port}}
        resources:
          requests:
            memory: 128Mi
            cpu: 350m
          limits:
            memory: 256Mi
            cpu: 500m
